const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const { getData } = require('../db/firebase');
const email = require('../utils/email');
const logger = require('../utils/logger');

function formatCurrency(amount) {
  return `Rp ${Number(amount).toLocaleString('id-ID')}`;
}

async function generateBrandedWeeklyPDF(report, workspaceConfig) {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([595.28, 841.89]);
  const { width } = page.getSize();
  const margin = 50;
  let y = 750;

  const businessName = workspaceConfig.businessName || 'Your Business';
  const brandedName = workspaceConfig.brandedReportName || businessName;

  page.drawText(brandedName, { x: margin, y, size: 22, font: boldFont, color: rgb(0.1, 0.1, 0.1) });
  y -= 10;
  page.drawText(`Weekly Report — ${report.date}`, { x: margin, y, size: 11, font, color: rgb(0.5, 0.5, 0.5) });
  y -= 10;
  page.drawText(`Prepared exclusively for ${businessName}`, { x: margin, y, size: 9, font, color: rgb(0.6, 0.6, 0.6) });
  y -= 30;

  page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 1, color: rgb(0.8, 0.8, 0.8) });
  y -= 25;

  const metrics = [
    { label: 'Conversations', value: String(report.conversations) },
    { label: 'New Customers', value: String(report.newCustomers) },
    { label: 'Revenue', value: report.revenueFormatted },
    { label: 'Invoices', value: String(report.invoicesGenerated) },
  ];

  const colW = (width - 2 * margin) / 4;
  metrics.forEach((m, i) => {
    const x = margin + i * colW;
    page.drawText(m.value, { x, y, size: 18, font: boldFont, color: rgb(0.2, 0.2, 0.2) });
    page.drawText(m.label, { x, y: y - 16, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
  });
  y -= 50;

  if (report.topCustomers?.length) {
    y -= 10;
    page.drawText('Top Customers', { x: margin, y, size: 13, font: boldFont, color: rgb(0.2, 0.2, 0.2) });
    y -= 20;

    const headers = ['Customer', 'Conversations'];
    const colX = [margin, width - margin - 80];
    page.drawText(headers[0], { x: colX[0], y, size: 10, font: boldFont, color: rgb(0.4, 0.4, 0.4) });
    page.drawText(headers[1], { x: colX[1], y, size: 10, font: boldFont, color: rgb(0.4, 0.4, 0.4) });
    y -= 12;
    page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
    y -= 12;

    report.topCustomers.slice(0, 5).forEach(c => {
      page.drawText(c.name, { x: colX[0], y, size: 10, font });
      page.drawText(String(c.messages), { x: colX[1], y, size: 10, font });
      y -= 16;
    });
  }

  y = 60;
  page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
  y -= 15;
  page.drawText('Generated by Chatty — AI Customer Service Platform', {
    x: margin, y, size: 8, font, color: rgb(0.6, 0.6, 0.6),
  });

  return Buffer.from(await doc.save());
}

async function generateWeeklyReport(workspaceId) {
  const workspace = await getData(`/workspaces/${workspaceId}/config`);
  if (!workspace) return null;

  const lastWeek = Date.now() - 7 * 86400000;

  const customers = await getData(`/workspaces/${workspaceId}/customers`);
  let totalConversations = 0;
  let newCustomers = 0;
  let totalRevenue = 0;
  let invoicesCount = 0;

  if (customers) {
    for (const [, customer] of Object.entries(customers)) {
      const messages = customer.messages;
      if (messages) {
        const recent = Object.values(messages).filter(m => m.timestamp > lastWeek);
        totalConversations += recent.length;
      }
      if (customer.firstContact > lastWeek) newCustomers++;
    }
  }

  const invoices = await getData(`/workspaces/${workspaceId}/invoices`);
  if (invoices) {
    for (const [, inv] of Object.entries(invoices)) {
      if (inv.status === 'paid' && (inv.paidAt || 0) > lastWeek) {
        totalRevenue += inv.total || 0;
        invoicesCount++;
      }
    }
  }

  const topCustomers = [];
  if (customers) {
    for (const [id, customer] of Object.entries(customers)) {
      const msgs = customer.messages ? Object.values(customer.messages) : [];
      const recentMsgs = msgs.filter(m => m.timestamp > lastWeek);
      if (recentMsgs.length > 0) {
        topCustomers.push({ id, name: customer.name || id, messages: Math.floor(recentMsgs.length / 2) });
      }
    }
    topCustomers.sort((a, b) => b.messages - a.messages).slice(0, 5);
  }

  return {
    date: new Date().toISOString().split('T')[0],
    businessName: workspace.businessName || 'Your Business',
    conversations: Math.floor(totalConversations / 2),
    newCustomers,
    invoicesGenerated: invoicesCount,
    revenue: totalRevenue,
    revenueFormatted: `Rp ${Number(totalRevenue).toLocaleString('id-ID')}`,
    topCustomers,
  };
}

async function sendWeeklyReport(workspaceId) {
  const report = await generateWeeklyReport(workspaceId);
  if (!report) return;

  const workspace = await getData(`/workspaces/${workspaceId}/config`);
  const isPro = workspace?.plan === 'pro';

  const topCustomersHtml = report.topCustomers.map(c =>
    `<tr><td style="padding: 6px; border-bottom: 1px solid #eee;">${c.name}</td><td style="padding: 6px; border-bottom: 1px solid #eee; text-align: right;">${c.messages}</td></tr>`
  ).join('');

  const emailHtml = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #333;">${report.businessName}</h2>
      <p style="color: #666;">Weekly Recap — ${report.date}</p>
      <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">💬 Conversations</td><td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;"><b>${report.conversations}</b></td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">🆕 New customers</td><td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;"><b>${report.newCustomers}</b></td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">💵 Revenue</td><td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;"><b>${report.revenueFormatted}</b></td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">📄 Invoices</td><td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;"><b>${report.invoicesGenerated}</b></td></tr>
      </table>
      ${topCustomersHtml ? `<h3 style="color: #555;">🌟 Top Customers</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr><th style="padding: 6px; border-bottom: 2px solid #ddd; text-align: left;">Customer</th><th style="padding: 6px; border-bottom: 2px solid #ddd; text-align: right;">Conversations</th></tr>
          ${topCustomersHtml}
        </table>` : ''}
      ${isPro ? '<p>📎 A branded PDF report is attached.</p>' : ''}
      <p style="color: #999; font-size: 12px; margin-top: 30px;">Sent by Chatty — AI Customer Service Platform</p>
    </div>
  `;

  let attachments = [];
  if (isPro) {
    try {
      const pdfBytes = await generateBrandedWeeklyPDF(report, workspace || {});
      attachments = [{
        content: pdfBytes.toString('base64'),
        filename: `Weekly-Report-${report.date}.pdf`,
        type: 'application/pdf',
        disposition: 'attachment',
      }];
    } catch (err) {
      logger.error('Branded PDF generation error', { workspaceId, error: err.message });
    }
  }

  if (workspace?.ownerEmail) {
    const sendObj = {
      to: workspace.ownerEmail,
      subject: `📊 ${report.businessName} — Weekly Recap`,
      html: emailHtml,
    };
    if (attachments.length) sendObj.attachments = attachments;

    await email.send(sendObj);
    logger.info('Weekly report sent', { workspaceId, brandedPdf: isPro });
  }
}

async function sendWeeklyReportsToAll() {
  const workspaces = await getData('/workspaces');
  if (!workspaces) return;

  for (const workspaceId of Object.keys(workspaces)) {
    await sendWeeklyReport(workspaceId);
  }
}

module.exports = { generateWeeklyReport, sendWeeklyReport, sendWeeklyReportsToAll };
